name: .NET

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore src/DestinyLife.sln
    - name: Build
      run: dotnet build src/DestinyLife.sln --no-restore
